export const merchantCategories =
  process.env.NODE_ENV === 'development'
    ? [
        'Retail',
        'Entertainment',
        'Cleaning Services',
        'Legal Services',
        'Real Estate',
        'Craft Breweries',
        'Education and Training',
        'Hotelier',
        'Automotive',
      ]
    : [
        'Hotelier',
        'Food and Beverage',
        'Retail',
        'E-commerce',
        'Travel and Tourism',
        'Entertainment',
        'Health and Wellness',
        'Real Estate',
        'Construction Services',
        'Transportation Services',
        'Education and Training',
        'Personal Care Services',
        'Automotive',
        'Art and Crafts',
        'Grocery and Supermarkets',
        'Pharmaceuticals',
        'Home Goods',
        'Fitness and Sports',
        'Florists',
        'Jewelry and Accessories',
        'Pet Services',
        'Office Supplies',
        'Electronics',
        'Media and Publishing',
        'Event Planning',
        'Cleaning Services',
        'Consulting Services',
        'Legal Services',
        'Financial Services',
        'Insurance Providers',
        'Technology Services',
        'Therapy and Counseling',
        'Craft Breweries',
        'Specialty Foods',
        'Photography and Videography',
      ];
