name: Deploy Deployment Amplify

on:
  workflow_dispatch:
  
permissions:
      id-token: write # This is required for aws oidc connection
      contents: read # This is required for actions/checkout
      pull-requests: write # This is required for gh bot to comment PR

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      APP_ID: ${{ secrets.AMPLIFY_APP_ID }}
      BRANCH_NAME: development

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies & build project
        run: |
          rm -rf node_modules package-lock.json
          npm cache clean --force
          npm install --legacy-peer-deps --save-dev
          npm run build
          npx esbuild next.config.ts --bundle --platform=node --outfile=next.config.js
          mkdir -p ./amplify-artifacts
          zip -r ./amplify-artifacts/app.zip .next public package.json next.config.js
          ZIP_PATH=./amplify-artifacts/app.zip


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.TF_EXEC_ROLE_DEV }}

      - name: Upload ZIP to Amplify
        run: |
          DEPLOYMENT_JSON=$(aws amplify create-deployment --app-id "$APP_ID" --branch-name "$BRANCH_NAME")
          UPLOAD_URL=$(echo $DEPLOYMENT_JSON | jq -r '.zipUploadUrl')
          JOB_ID=$(echo $DEPLOYMENT_JSON | jq -r '.jobId')
          curl -T "$ZIP_PATH" "$UPLOAD_URL"

      - name: Publish Deployment to Amplify
        run: |
          aws amplify start-deployment \
            --app-id "$APP_ID" \
            --branch-name "$BRANCH_NAME" \
            --job-id "$JOB_ID"
