name: Deploy SSR app to Amplify

on:
  push:
    branches:
      - development
  workflow_dispatch:

env:
  ROLE_ARN: ${{ secrets.TF_EXEC_ROLE_DEV  }}
  AWS_REGION: eu-west-1                  


jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          role-session-name: github-actions-session
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies and build app
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Run Tests
        run: npm test

      - name: Trigger Amplify Build
        run: curl -X POST -d {} ${{ secrets.AMPLIFY_WEBHOOK_URL }}        

